spring.datasource.url=${jdbc:postgresql://dpg-d7n5lemgvqtc73am8b6g-a.frankfurt-postgres.render.com/punktescanner_db}
spring.datasource.username=${punktescanner_db_user}
spring.datasource.password=${mWiiJwICjjW4lnia2ZzUobDZdksDZr0M}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=${PORT:8081}
spring.thymeleaf.check-template-location=false
spring.devtools.restart.enabled=false